### ISSUE TITLE
Split or mark client + server libraries

### ISSUE THREAD

**Issue by mnpenner** [chentsulin/awesome-graphql#200]
It's hard to tell which of these libraries are client implementations or server implementations. For example, I'm looking for a GraphQL *client* for PHP but most of those appear to be server implementations -- I can't tell what's what.

**Comment by chentsulin** [comment]
Do you want to contribute to this? This is definite a good idea.

**Comment by wilmoore** [comment]
I like the suggestion @mnpenner - I was planning to do this when I was looking at this list a few days ago, so your suggestion reminded me to get started this morning. I will continue iterating once #447 is merged.
