### ISSUE TITLE
Remove graphql-elixir in favor of Absinthe only

### ISSUE THREAD

**Issue by yordis** [chentsulin/awesome-graphql#314]
This package is deprecated at this point https://github.com/graphql-elixir/graphql in favor of using Absinthe

**Comment by chentsulin** [comment]
where is the deprecated message?

**Comment by yordis** [comment]
See the last updates and movement on the package.

On Elixir ecosystem Absinthe is the way to go (maybe it would help to just leave the one that is in active development) 

But close it if you think otherwise, this is more a suggestion since the package is pretty much dead

**Comment by TreTuna** [comment]
I'm going to add a note that it is no longer maintained but will keep it on the list as people may yet still be able to learn from its implementation.
