### ISSUE TITLE
Add graphql-spqr

### ISSUE THREAD

**Issue by kaqqao** [chentsulin/awesome-graphql#315]
Please add [GraphQL-SPQR](https://github.com/leangen/graphql-spqr) to the Java section. It's been an active project for years.

GraphQL SPQR is a simple-to-use library for rapid development of GraphQL APIs in Java, in the code-first approach. It integrates easily into any Java based stack, with examples using Spring Boot and Spring MVC provided.

It is featured on Awesome graphql-java and has been the subject of multiple conference talks:

* [Amsterdam Codemotion 2017](https://www.youtube.com/watch?v=1zIHHi2MaQE)
* [Devoxx Belgium 2018](https://www.youtube.com/watch?v=iyt7PwkUWQA)

I made a [PR](https://github.com/chentsulin/awesome-graphql/pull/207) that's been rotting for almost a year now, so I opened an issue to try getting some attention.

**Comment by Javabien** [comment]
I cannot believe this PR is almost two years old ... this project is really amazing and very active!

**Comment by kaqqao** [comment]
@Javabien That makes two of us... I have no clue what's going on.

**Comment by TreTuna** [comment]
@kaqqao Last time we spoke on your PR back in December you said you would bring it up to date, however, this was not done until 8 days ago. 

I am the only maintainer keeping an eye on this anymore and my wife and I recently welcomed a new child to our family, hence I haven't as active as of late. I missed your update and it seems there are new conflicts in the PR. If you can resolve those I would be happy to get this merged.

**Comment by Javabien** [comment]
Congrats for your new child 😉

**Comment by TreTuna** [comment]
Brought this up to date myself and merged it.

**Comment by kaqqao** [comment]
@TreTuna Thanks a bunch! Terribly sorry if I came off as pushy! I join in the congratulations 😊

I forgot to update the PR but noticed someone else made a fresh one. I guess you've figured it out anyway. Thanks again, much appreciated!

**Comment by TreTuna** [comment]
@kaqqao All good! I don't like seeing all the PRs sitting here either, it's why I ended up wanting to be a collaborator back in Dec and working on these when I do get a little time here and there. 😄
