### ISSUE TITLE
Please add `archen` - a library building GraphQL service on existing database with defining NOTHING new

### ISSUE THREAD

**Issue by MewX** [chentsulin/awesome-graphql#364]
I just found a library called Archen: https://github.com/fangwd/archen/

Pros:
1. Define NOTHING to build GraphQL service on your existing database! SO EASY!
2. Generic structure and scalable for future support
3. Override options to control GraphQL service security.

Cons:
1. The documentation is not complete, and the authors are working on that.
2. The latest version supports mysql only (and the authors are working on supporting `sqlite3` and other databases)

I reckon this library will be very helpful in GraphQL community.

Here's an example:

```
const {graphql} = require('graphql');
const {Archen} = require('archen');

const archen = new Archen({
    database: {
        dialect: 'mysql',
        connection: {
            host: 'localhost',
            user: 'root',
            password: 'root',
            database: 'graduation_project',
            timezone: 'Z',
            connectionLimit: 10
        }
    }
});

archen.getSchemaInfo().then(() => {
    const [schema, rootValue, accessor] = [
        archen.graphql.getSchema(),
        archen.graphql.getRootValue(),
        archen.getAccessor()
    ];

    const query1 = `
    {
      task(where: {id: 1001}) {
        name,
        content,
        type,
        holder {
          name
        }
      }
    }`;
    const query2 = `
    {
      tasks {
        id,
        name,
        content,
        type,
        holder {
          name
        }
      }
    }`;

    graphql(schema, query1, rootValue, {accessor}).then(response => {
        console.log(JSON.stringify(response, null, 2));
    });
});
```

They provide another two examples as well: https://github.com/fangwd/archen/blob/master/example/

**Comment by chentsulin** [comment]
Thanks for the suggestion, but I'm going to pass on this. This is a curation, so I unfortunately can't include everything.
