### ISSUE TITLE
TypeScript libraries section

### ISSUE THREAD

**Issue by MichalLytek** [chentsulin/awesome-graphql#532]
A long time ago I've added a few TypeScript libraries for GraphQL:
https://github.com/chentsulin/awesome-graphql/pull/327

But now I see only Nexus...

![image](https://user-images.githubusercontent.com/10618781/67749398-64048180-fa2d-11e9-828a-fd1712443684.png)

Why they are removed? 😕

**Comment by rlancer** [comment]
TypeGraphQL should be on there

**Comment by chentsulin** [comment]
This mistake has been fixed.
