### ISSUE TITLE
Add graphql-kotlin

### ISSUE THREAD

**Issue by elenigen** [chentsulin/awesome-graphql#542]
Hi, I would like to help to review and merge PRs if you don't mind, I could be a contributor.  I would first merge my own 😉 https://github.com/chentsulin/awesome-graphql/pull/539

**Comment by valoricDe** [comment]
While your on it can you add https://github.com/Netflix/dgs-framework as well?

**Comment by elenigen** [comment]
@valoricDe sorry, this PR has been merged a year ago already, feel free to open a new one! 😃

**Comment by valoricDe** [comment]
Ups xD, ok I'll do
