### ISSUE TITLE
please delete the items which star less then 1k

### ISSUE THREAD

**Issue by lushi118** [chentsulin/awesome-graphql#583]
I think there are too many redundant items in the list ,especially the  items which star less then 1k,which are generally of little reference value

**Comment by ppwfx** [comment]
awesome lists give small projects a chance to grow their community. I'm not sure if it would benefit the ecosystem if new projects would simply be filtered out

**Comment by z-ax** [comment]
Agree with @ppwfx, amount of stars can't be the only criteria. New well-tested projects on TypeScript might already me pretty awesome.

**Comment by TreTuna** [comment]
When looking at items to judge if they are acceptable I do not just look at star count. As @ppwfx said, this is also to allow newer/smaller projects to get exposure and grow. I don't get a lot of time to groom through all of this, so I primarily look at the following items:

Does it have proper documentation? (If a user doesn't know what the project is or how to use it, it's not going to be helpful.)
Is it currently maintained?
How frequent are the updates?
Are the links broken?

There are a few smaller things to look at as well, which does include star count, but those three are the top priorities in seeing if something makes it on the list.
