### ISSUE TITLE
Missing gqless and babel-blade in the js clients list

### ISSUE THREAD

**Issue by valoricDe** [chentsulin/awesome-graphql#635]
Maybe we can add
https://github.com/gqless/gqless
and 
https://github.com/babel-blade/babel-blade
to the list?

**Comment by valoricDe** [comment]
And https://github.com/Netflix/dgs-framework

**Comment by chentsulin** [comment]
`babel-blade` is still a WIP project, so I'm not going to add it.
`gqless` and `dgs-framework` have been added to the list.
