### ISSUE TITLE
Add more admins

### ISSUE THREAD

**Issue by elenigen** [chentsulin/awesome-graphql#636]
Hi, I see that we are at 99 opened PRs, sounds like we should have more admin to review the PRs, so I propose myself. ✌️

**Comment by setchy** [comment]
I'd also gladly volunteer to help maintain the repository 😎

**Comment by mjarkk** [comment]
Pinging @chentsulin

**Comment by elenigen** [comment]
@setchy It looks like we are helping each other 😉 
https://github.com/thoughtworks/build-your-own-radar/issues/177#issuecomment-970490430

**Comment by chentsulin** [comment]
Hi @elenigen @setchy,
I invited both you as project collaborator, so feel free to help reviewing the PRs. 
I'm still open to more admins especially GraphQL experts in multiple programming languages.

**Comment by setchy** [comment]
Thank you @chentsulin

**Comment by elenigen** [comment]
Thanks!

**Comment by j2346391** [comment]
simebody helped me?
