### ISSUE TITLE
Weird C/C++ Library link

### ISSUE THREAD

**Issue by BenDiuguid** [chentsulin/awesome-graphql#90]
The link in the table of contents (https://github.com/chentsulin/awesome-graphql/blob/master/README.md#lib-c) Doesn't actually link to the C/C++ lib section.

The link that does work is https://github.com/chentsulin/awesome-graphql/blob/master/README.md#cc-libraries

I was going to submit a PR for this simple fix, but the `Readme.md` looks correct? Strange

**Comment by chentsulin** [comment]
Fixed via https://github.com/chentsulin/awesome-graphql/commit/397526082160478bcff2450ffbe20e23810ff1f8

Thanks!
