### ISSUE TITLE
Please merge PR's

### ISSUE THREAD

**Issue by aschrijver** [chentsulin/awesome-graphql#99]
Hi @chentsulin ,
I see you are a very, very active committer on Github. Kudos to you :+1: 
Could you, or another maintainer of this project, spare a couple of minutes to push some PR's through?

Thanks a bunch!

**Comment by stubailo** [comment]
I'd be happy to help merge some PRs and organize the repository if added as a collaborator. I've worked in a similar capacity on graphql.org: https://github.com/graphql/graphql.github.io/commits/source?author=stubailo

**Comment by stubailo** [comment]
Great, just got access. On it!

**Comment by aschrijver** [comment]
Thank you @stubailo :+1:
